### ISSUE TITLE
package assertionerror

### ISSUE THREAD

**Issue by devYurim** [CMU-TBD/SocNavBench#24]
I tried to install the package as a guide and test sacardl model.
The following assertionerror occurred.
`(cardl) ailab@aliab:/home/ailab-yurim/cardl/SocNavBench$ PYTHONPATH='.' python3 joystick/joystick_client.py --algo "Sacadrl"
Traceback (most recent call last):
  File "joystick/joystick_client.py", line 11, in <module>
    from sacadrl.joystick_sacadrl import JoystickSACADRL
  File "/home/ailab-yurim/cardl/SocNavBench/joystick/sacadrl/joystick_sacadrl.py", line 16, in <module>
    from gym_collision_avoidance.envs.agent import Agent
  File "/home/ailab/anaconda3/envs/cardl/lib/python3.7/site-packages/gym_collision_avoidance/envs/__init__.py", line 17, in <module>
    assert(callable(config_class))
AssertionError`

The package was installed as below.

![image](https://user-images.githubusercontent.com/20412850/170928178-2db39a8c-2d87-4191-bbc1-22e400a00d64.png)

The file is located in the directory below.
SocNavBench> joystick > 'gym-collision-avoidance'

How to solve it?

**Comment by ajdroid** [comment]
Hi, have you installed the baselines from [this repository](https://github.com/CMU-TBD/SocNavBench-baselines)? 
If so, can you try one of the other baselines to see if that one works?
Do the unit tests for socnav work as outlined in the README?
